import enum
import uuid

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import UUID

from app.core.database import Base


class InterfaceOperStatus(str, enum.Enum):
    UP = "up"
    DOWN = "down"


class InterfaceStatus(Base):
    """One row per detected interface (port) status *change*, not one row
    per poll -- this is a transition log, not a metric timeseries (see
    VictoriaMetrics, via app.core.vm_client, for the per-poll aggregate
    numbers). Written by app.services.metrics_service._sync_interface_status
    whenever a poll's ifOperStatus for a given ifIndex differs from the
    most recent row on file for that (device_id, if_index) pair.

    This is what powers:
      - "Interface Status History" on the device detail / topology panel
        (every flap, with timestamps).
      - The NOC dashboard's live "ports currently down" list (the latest
        row per if_index where status == down).
      - The "Interface Down" / port-flap Alerts raised in metrics_service,
        which reference the same if_index/if_descr vocabulary.
    """

    __tablename__ = "interface_statuses"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    device_id = Column(UUID(as_uuid=True), ForeignKey("devices.id"), nullable=False, index=True)

    if_index = Column(String, nullable=False)  # SNMP ifIndex, kept as string (matches snmp_service walk keys)
    if_descr = Column(String, nullable=False)  # ifDescr at the time of this reading, e.g. "GigabitEthernet0/1"

    status = Column(Enum(InterfaceOperStatus, values_callable=lambda obj: [e.value for e in obj]), nullable=False)
    previous_status = Column(Enum(InterfaceOperStatus, values_callable=lambda obj: [e.value for e in obj]), nullable=True)  # null on the very first-ever reading

    # True for every row generated by an actual detected *change*. Kept as
    # an explicit column (rather than inferring "is this the current row")
    # so a future "only show transitions" history filter doesn't need a
    # self-join -- always true today since this table is transition-only,
    # but keeps the door open for periodic heartbeat rows without a schema
    # change later.
    is_transition = Column(Boolean, nullable=False, default=True, server_default="true")

    changed_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
