"""Idempotency helpers for Alembic migrations.

Note: this module lives at backend/migration_helpers.py (not inside the
alembic/ package) because alembic.ini sets prepend_sys_path=. and
importing it as `alembic.idempotent` would shadow/collide with the
installed third-party `alembic` package itself.

Why this exists
----------------
`0001_baseline.py` calls `Base.metadata.create_all(bind=bind, checkfirst=True)`
using the **current** models at migration time. Since the models module is
kept up to date with the latest schema (not the schema as of each historical
migration), a completely fresh database gets *every* table/column that
exists in today's models the moment 0001 runs -- including tables and
columns that were "added" by 0002, 0007, 0008, 85cec3c5accf, etc.

Every migration after 0001 was originally autogenerated against an
*existing, pre-baseline* database (one that had drifted via the old
`create_all()`-on-startup pattern) and unconditionally calls
`op.create_table` / `op.add_column` / `op.create_index` /
`op.create_foreign_key`. On a fresh install those objects already exist
courtesy of 0001, so the raw calls raise `DuplicateTable` /
`DuplicateColumn` / `DuplicateObject` and the whole migration chain -- and
therefore every fresh `docker compose up --build` or local install -- fails
before the app ever starts.

These helpers make the *upgrade* path idempotent: skip the operation if the
target already exists, otherwise perform it exactly as before. Downgrades
are left untouched since they only run against a database that has already
had the corresponding upgrade applied.
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


def _inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def table_exists(table_name: str) -> bool:
    return table_name in _inspector().get_table_names()


def column_exists(table_name: str, column_name: str) -> bool:
    if not table_exists(table_name):
        return False
    return column_name in {c["name"] for c in _inspector().get_columns(table_name)}


def index_exists(table_name: str, index_name: str) -> bool:
    if not table_exists(table_name):
        return False
    return index_name in {ix["name"] for ix in _inspector().get_indexes(table_name)}


def fk_exists(table_name: str, fk_name: str) -> bool:
    if not table_exists(table_name):
        return False
    return fk_name in {fk["name"] for fk in _inspector().get_foreign_keys(table_name)}


def enum_type_exists(type_name: str) -> bool:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return False
    result = bind.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = :name"), {"name": type_name}
    )
    return result.first() is not None


def create_table_if_missing(name: str, *columns, **kw) -> None:
    if table_exists(name):
        return
    op.create_table(name, *columns, **kw)


def add_column_if_missing(table_name: str, column: sa.Column) -> None:
    if column_exists(table_name, column.name):
        return
    op.add_column(table_name, column)


def create_index_if_missing(index_name: str, table_name: str, columns, **kw) -> None:
    if index_exists(table_name, index_name):
        return
    op.create_index(index_name, table_name, columns, **kw)


def create_foreign_key_if_missing(fk_name: str, source_table: str, *args, **kw) -> None:
    if fk_name and fk_exists(source_table, fk_name):
        return
    op.create_foreign_key(fk_name, source_table, *args, **kw)


def drop_column_if_exists(table_name: str, column_name: str) -> None:
    if not column_exists(table_name, column_name):
        return
    op.drop_column(table_name, column_name)


def drop_index_if_exists(index_name: str, table_name: str) -> None:
    if not index_exists(table_name, index_name):
        return
    op.drop_index(index_name, table_name=table_name)
