"""add_telemetry_tables

Revision ID: 85cec3c5accf
Revises: 0006
Create Date: 2026-07-31 16:05:01.009221
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85cec3c5accf'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='alertseverity'), nullable=False),
    sa.Column('source', sa.Enum('SNMP_TRAP', 'HEALTH_POLL', 'DRIFT', 'PROTOCOL_FAILURE', name='alertsource'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_table('device_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('cpu_utilization_pct', sa.Float(), nullable=True),
    sa.Column('memory_utilization_pct', sa.Float(), nullable=True),
    sa.Column('interface_utilization_pct', sa.Float(), nullable=True),
    sa.Column('interface_errors', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('fan_status', sa.String(), nullable=True),
    sa.Column('power_supply_status', sa.String(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('interface_octets_total', sa.BigInteger(), nullable=True),
    sa.Column('interface_speed_bps', sa.BigInteger(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_color', sa.Enum('GREEN', 'YELLOW', 'RED', name='healthcolor'), nullable=True),
    sa.Column('polled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_metrics_device_id'), 'device_metrics', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_metrics_polled_at'), 'device_metrics', ['polled_at'], unique=False)
    op.create_table('protocol_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('protocol', sa.Enum('NETCONF', 'RESTCONF', 'SNMP', name='protocolname'), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_operations_created_at'), 'protocol_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_protocol_operations_device_id'), 'protocol_operations', ['device_id'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_logs_deployment_id'), 'deployment_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_logs_timestamp'), 'deployment_logs', ['timestamp'], unique=False)
    op.add_column('config_drifts', sa.Column('baseline', sa.Enum('GOLDEN_CONFIG', 'PREVIOUS_BACKUP', name='driftbaseline'), nullable=False))
    op.add_column('config_drifts', sa.Column('diff_text', sa.Text(), nullable=False))
    op.add_column('config_drifts', sa.Column('added_lines', sa.Integer(), nullable=False))
    op.add_column('config_drifts', sa.Column('removed_lines', sa.Integer(), nullable=False))
    op.add_column('config_drifts', sa.Column('modified_lines', sa.Integer(), nullable=False))
    op.add_column('config_drifts', sa.Column('risk_score', sa.Integer(), nullable=False))
    op.add_column('config_drifts', sa.Column('compliance_score', sa.Integer(), nullable=False))
    op.add_column('config_drifts', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('config_drifts', sa.Column('status', sa.Enum('OPEN', 'APPROVED', 'ROLLED_BACK', 'DISMISSED', name='driftstatus'), nullable=False))
    op.add_column('config_drifts', sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_config_drifts_detected_at'), 'config_drifts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_config_drifts_device_id'), 'config_drifts', ['device_id'], unique=False)
    op.drop_constraint('config_drifts_baseline_snapshot_id_fkey', 'config_drifts', type_='foreignkey')
    op.drop_column('config_drifts', 'checked_at')
    op.drop_column('config_drifts', 'detail')
    op.drop_column('config_drifts', 'baseline_snapshot_id')
    op.drop_column('config_drifts', 'resolved_at')
    op.drop_column('config_drifts', 'lines_changed')
    op.drop_column('config_drifts', 'drifted')
    op.drop_column('config_drifts', 'resolved_by')
    op.drop_column('config_drifts', 'triggered_by')
    op.drop_column('config_drifts', 'resolved')
    op.drop_column('config_drifts', 'diff')
    op.add_column('devices', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('model', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('os_version', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('supports_netconf', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('devices', sa.Column('supports_restconf', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('devices', sa.Column('supports_snmp', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('devices', sa.Column('netconf_port', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('restconf_url', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('snmp_version', sa.Enum('V1', 'V2C', 'V3', name='snmpversion'), nullable=True))
    op.add_column('devices', sa.Column('snmp_community_ref', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('snmp_username', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('snmp_auth_credential_ref', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('snmp_privacy_credential_ref', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('capabilities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'capabilities')
    op.drop_column('devices', 'snmp_privacy_credential_ref')
    op.drop_column('devices', 'snmp_auth_credential_ref')
    op.drop_column('devices', 'snmp_username')
    op.drop_column('devices', 'snmp_community_ref')
    op.drop_column('devices', 'snmp_version')
    op.drop_column('devices', 'restconf_url')
    op.drop_column('devices', 'netconf_port')
    op.drop_column('devices', 'supports_snmp')
    op.drop_column('devices', 'supports_restconf')
    op.drop_column('devices', 'supports_netconf')
    op.drop_column('devices', 'os_version')
    op.drop_column('devices', 'serial_number')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'platform')
    op.add_column('config_drifts', sa.Column('diff', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('config_drifts', sa.Column('resolved', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('config_drifts', sa.Column('triggered_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('config_drifts', sa.Column('resolved_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('config_drifts', sa.Column('drifted', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('config_drifts', sa.Column('lines_changed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('config_drifts', sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('config_drifts', sa.Column('baseline_snapshot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('config_drifts', sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('config_drifts', sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('config_drifts_baseline_snapshot_id_fkey', 'config_drifts', 'config_snapshots', ['baseline_snapshot_id'], ['id'])
    op.drop_index(op.f('ix_config_drifts_device_id'), table_name='config_drifts')
    op.drop_index(op.f('ix_config_drifts_detected_at'), table_name='config_drifts')
    op.drop_column('config_drifts', 'detected_at')
    op.drop_column('config_drifts', 'status')
    op.drop_column('config_drifts', 'ai_summary')
    op.drop_column('config_drifts', 'compliance_score')
    op.drop_column('config_drifts', 'risk_score')
    op.drop_column('config_drifts', 'modified_lines')
    op.drop_column('config_drifts', 'removed_lines')
    op.drop_column('config_drifts', 'added_lines')
    op.drop_column('config_drifts', 'diff_text')
    op.drop_column('config_drifts', 'baseline')
    op.drop_index(op.f('ix_deployment_logs_timestamp'), table_name='deployment_logs')
    op.drop_index(op.f('ix_deployment_logs_deployment_id'), table_name='deployment_logs')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_protocol_operations_device_id'), table_name='protocol_operations')
    op.drop_index(op.f('ix_protocol_operations_created_at'), table_name='protocol_operations')
    op.drop_table('protocol_operations')
    op.drop_index(op.f('ix_device_metrics_polled_at'), table_name='device_metrics')
    op.drop_index(op.f('ix_device_metrics_device_id'), table_name='device_metrics')
    op.drop_table('device_metrics')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
