from fastapi import APIRouter

from app.api import (
    alert_rules,
    alert_runbooks,
    alert_snoozes,
    alerts,
    approval_delegates,
    audit,
    auth,
    backups,
    change_requests,
    chatops,
    compliance_baselines,
    config_intents,
    config_management,
    config_search,
    config_templates,
    dashboard,
    deployments,
    device_groups,
    devices,
    drift,
    escalation_policies,
    firmware_upgrades,
    flows,
    gitops,
    global_search,
    gnmi,
    gns3,
    health,
    incidents,
    ipam,
    jit_access,
    jobs,
    maintenance_windows,
    metrics,
    network_discovery,
    notification,
    notification_settings,
    on_call_schedules,
    path_trace,
    push_subscriptions,
    rbac,
    recurring_maintenance_schedules,
    reports,
    secrets_rotation,
    sso,
    syslog,
    tenant_board,
    tenant_digest,
    tenants,
    terminal,
    terminal_recordings,
    topology,
    user_management,
    war_room,
    webhooks,
    wireless,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(approval_delegates.router)
api_router.include_router(sso.router)
api_router.include_router(health.router)
api_router.include_router(devices.router)
api_router.include_router(device_groups.router)
api_router.include_router(global_search.router)
api_router.include_router(alert_snoozes.router)
api_router.include_router(config_management.router)
api_router.include_router(config_management.snapshot_policy_router)
api_router.include_router(config_search.router)
api_router.include_router(change_requests.router)
api_router.include_router(audit.router)
api_router.include_router(dashboard.router)
api_router.include_router(deployments.router)
api_router.include_router(jobs.router)
api_router.include_router(drift.router)
api_router.include_router(metrics.router)
api_router.include_router(alerts.router)
api_router.include_router(alert_rules.router)
api_router.include_router(alert_runbooks.router)
api_router.include_router(escalation_policies.router)
api_router.include_router(on_call_schedules.router)
api_router.include_router(incidents.router)
api_router.include_router(jit_access.router)
api_router.include_router(gns3.router)
api_router.include_router(notification.router)
api_router.include_router(notification_settings.router)
api_router.include_router(reports.router)
api_router.include_router(rbac.router)
api_router.include_router(secrets_rotation.router)
api_router.include_router(topology.router)
api_router.include_router(war_room.router)
api_router.include_router(terminal.router)
api_router.include_router(terminal_recordings.router)
api_router.include_router(compliance_baselines.router)
api_router.include_router(config_templates.router)
api_router.include_router(syslog.router)
api_router.include_router(path_trace.router)
api_router.include_router(maintenance_windows.router)
api_router.include_router(recurring_maintenance_schedules.router)
api_router.include_router(firmware_upgrades.router)
api_router.include_router(flows.router)
api_router.include_router(gnmi.router)
api_router.include_router(webhooks.router)
api_router.include_router(config_intents.router)
api_router.include_router(chatops.router)
api_router.include_router(gitops.router)
api_router.include_router(ipam.router)
api_router.include_router(push_subscriptions.router)
api_router.include_router(user_management.router)
api_router.include_router(backups.router)
api_router.include_router(network_discovery.router)
api_router.include_router(tenant_board.router)
api_router.include_router(tenants.router)
api_router.include_router(tenant_digest.router)
api_router.include_router(wireless.router)
