from fastapi import APIRouter

from app.api import (
    alert_rules,
    alert_snoozes,
    alerts,
    audit,
    auth,
    change_requests,
    compliance_baselines,
    config_intents,
    config_management,
    config_search,
    config_templates,
    dashboard,
    deployments,
    device_groups,
    devices,
    drift,
    escalation_policies,
    firmware_upgrades,
    flows,
    global_search,
    gns3,
    health,
    incidents,
    jit_access,
    jobs,
    maintenance_windows,
    metrics,
    notification,
    path_trace,
    rbac,
    reports,
    secrets_rotation,
    syslog,
    terminal,
    topology,
    webhooks,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(health.router)
api_router.include_router(devices.router)
api_router.include_router(device_groups.router)
api_router.include_router(global_search.router)
api_router.include_router(alert_snoozes.router)
api_router.include_router(config_management.router)
api_router.include_router(config_management.snapshot_policy_router)
api_router.include_router(config_search.router)
api_router.include_router(change_requests.router)
api_router.include_router(audit.router)
api_router.include_router(dashboard.router)
api_router.include_router(deployments.router)
api_router.include_router(jobs.router)
api_router.include_router(drift.router)
api_router.include_router(metrics.router)
api_router.include_router(alerts.router)
api_router.include_router(alert_rules.router)
api_router.include_router(escalation_policies.router)
api_router.include_router(incidents.router)
api_router.include_router(jit_access.router)
api_router.include_router(gns3.router)
api_router.include_router(notification.router)
api_router.include_router(reports.router)
api_router.include_router(rbac.router)
api_router.include_router(secrets_rotation.router)
api_router.include_router(topology.router)
api_router.include_router(terminal.router)
api_router.include_router(compliance_baselines.router)
api_router.include_router(config_templates.router)
api_router.include_router(syslog.router)
api_router.include_router(path_trace.router)
api_router.include_router(maintenance_windows.router)
api_router.include_router(firmware_upgrades.router)
api_router.include_router(flows.router)
api_router.include_router(webhooks.router)
api_router.include_router(config_intents.router)
